### ISSUE TITLE
ANDROID: GooglePlay 64-bit requirement

### ISSUE THREAD

**Issue by zomagic** [MikeHart66/cerberus#66]
I’d like to contribute to cerberusX. 
I manage to compile 64bit liblangutil NDK library for 64bit android.
It should be in our android target ..targets\android\template\gradletemplate\app\src\main\jnilibs

**Comment by MikeHart66** [comment]
Like I said, I would love to include this. But it important that we are able to compile them on our own. Could you share also the way how you were building them?

**Comment by MikeHart66** [comment]
Added these to github a while ago
