### ISSUE TITLE
WritePixel / DrawImage not displaying alpha - mojo2

### ISSUE THREAD

**Issue by pantson** [MikeHart66/cerberus#75]
When writing (alpha shl 24 + $ffffff) to a databuffer and then writing that to an img, when drawn it doesnt display the alpha and just draws solid.
This happens in GLFW and HTML targets

The attached demo,will set the image to either RED GREEN BLUE or WHITE and draw it to the screen. (press R G B or W for the relevant image). This image is drawn on the left

In data there is also an image it loads that is set to WHITE with variable alpha. This draws correctly. See the right of the screen

This seems to only happen when using $FFFFFF white
[test_writepixel.zip](https://github.com/MikeHart66/cerberus/files/3675733/test_writepixel.zip)

**Comment by Holzchopf** [comment]
mojo2 requires pixel data to be premultiplied. Use [DrawList.PremultiplyArgb2Abgr](https://www.cerberus-x.com/cxDocs/Modules_mojo2.graphics_DrawList.html#PremultiplyArgb2Abgr(Int)) to convert your color value accordingly. Also - but you seem to have noticed - mojo2 uses BGR internally, not RGB.

e.g. in your example code
data.PokeInt(4*x + y*4*256, DrawList.PremultiplyArgb2Abgr(y Shl 24 + col))

**Comment by pantson** [comment]
thank you. 
this explains a lot in my code ;-)
