### ISSUE TITLE
Mojo2.font.Load dont allow image filters to be passed in

### ISSUE THREAD

**Issue by pantson** [MikeHart66/cerberus#76]
Currently font.load loads in font image sheets with default filter. This means that scaling a font is always filtered. It be nice to pass in the image filter
Example - Turn off filtering while loading font
fnt = Font.Load(file,0)

in mojo2.graphics.font 
line 1380	Function Load:Font(url:String,flags:Int=Image.Filter)
line1453 _pages[pageNum] = Image.Load(filename,0,0,flags)

**Comment by MikeHart66** [comment]
Damn i didn't see this before. Will fix that.

**Comment by MikeHart66** [comment]
Added,
